ansible_connection: ENC[AES256_GCM,data:s9ClvdM=,iv:4KObq9lczhSd9fpVdehxCbUAa3pEoc3oZBZYVKYPoLE=,tag:MVRSH8rX6xnmx7JQnoodAQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sObt7aFBxeRt2pqB3RsnXw==,iv:Vp8EM7whpQ2s42xPaWM6Ue2QbjfZf0gzfO0/ZMXCL94=,tag:xjg9q8m/NQLdymcC7JsNfg==,type:str]
ansible_user: ENC[AES256_GCM,data:bwBi32z+,iv:KhO/uQKrlVcwn9Bf+zsZ+tglVpW36Af1SS92N3v4kf8=,tag:n/p6llz3zq5VDV6BdlTX4w==,type:str]
asdf_user: ENC[AES256_GCM,data:jxdEA+6Z,iv:+NhIeYnzQoK1vKgBxWyFlzjS6sp93K4BZ6Nl55h7JoU=,tag:iBMPncQ4axpotU1TWKWc9Q==,type:str]
asdf_shell: ENC[AES256_GCM,data:Kd0L,iv:lahlJxnK2DW2VnBCRVSlEmgyl6zXzZNPb0UVrV2AfpM=,tag:GpHXukLStOs4uyXkIRA7Sw==,type:str]
yazi_user: ENC[AES256_GCM,data:YOTmmiO8,iv:CaopEHU4T8ayPetfg1DeSFAjnmpKNbaE2dshVGX4oH4=,tag:VQkxq9x04QB+zCIKKSouLQ==,type:str]
yazi_shell: ENC[AES256_GCM,data:cnpa,iv:2YerCHU39I/e5BZ10IiPd2TT8FW1Q8l0/wSnYdgVkx8=,tag:oj9HgmRJxM0jso3i22u9CA==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:JlCj8Yk9p5m4Gg==,iv:9jB1rXoh3l9oMbdi6uD58W1wF5uV2DMmSIfy9AHXGwg=,tag:kPlDj9L139tOTr181XIBIQ==,type:str]
asdf_plugins:
    - name: ENC[AES256_GCM,data:xgA=,iv:kGabY7tS5gXXN/OQVViqUht/gWTnbMR78CJBIdlS/3E=,tag:Zpxn9O+1A9keREVl5saXTg==,type:str]
      version: ENC[AES256_GCM,data:0w4nbOk=,iv:d2z0RoNty0mTlr7WXRRebXhISFu5gV6X6j3uOGpwG9c=,tag:AqUKjROwd/iuVIIOjq63Yw==,type:str]
    - name: ENC[AES256_GCM,data:5K4=,iv:bFQk9VRhVcarTLYSoX0ZiFbE1b8wx+2OEpD0HRCDMTI=,tag:S0VIbOIY6U+BmlJOoCwtRw==,type:str]
      version: ENC[AES256_GCM,data:hP8n6u8a,iv:yS9vw5kge8HNeg3hlSn7/NfFu+ECsq7aTM0IVL0zR3c=,tag:gvm2OR9GMGip0jASrKZTtQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:52:16Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwFxfi3q9eJfRdZXZ14RWvdSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2qV7GbMMRmRCwRofAgEQgDvy4lqJd7BA5KY9Fc/2ms5LKAg5uqEO53F3pu1zXjAfkbUPipKW2Rxf1+YtUDHxLOV0ckMmz0J0YeRmzA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV2VBVm5LVDNwMnRHNGpR
            S1JkYkRkZjJCdmRWV2dFUlNjeGt0TDJrWmlvCjNVMHBob2h6VWNRR3gvVnpibGta
            dFNhT1Q3a0hBb0kwMlkweTlUell3UzgKLS0tIERxc0c0NUJZb1BsL2FvRTZDd3dY
            ckliQlJiSEhwb1lsTHlabXJyTnlqRXcKisAss0q7f9wdAUm9mBCF09ErWHVJnRHV
            eKVtIZb4DfwuqFA1ORR8/qh3dkww4SzItv3fv45wjkL8hww+5Ldq3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:52:18Z"
    mac: ENC[AES256_GCM,data:5+Z9M7BcmPrHxoqmMR6jX6N6xCyMIGMyqjw749LAneYeqoWuxVSDSDKf4bHGbfEgsJ6LekRKaNdhmOyZ7lf2Gzzxgy67/t4gLdDB2gs9sFMv3SQinLzHv2zU618CQw8TEx8lSPbp2SDOKBrz8pnLw4JCVwLo2bIC4asslAZpHJk=,iv:E4h5pZ9MO7v8aP+vUFQzY5vI3xmWiBmPDr7H4JgzQZA=,tag:ZolySeyOcdu7fAzlegiO1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
