ansible_user: ENC[AES256_GCM,data:F7cT4HaKcxjcfT7W,iv:0AKzV3HaqdnTT+MYEAzh260RMzIAsXnbUlWvafvOk14=,tag:49J2s4nGQM36xXlQtaQvXg==,type:str]
desired_ip_address: ENC[AES256_GCM,data:RCRknfUmumqEtUKZ8VTr,iv:HiQ++8MkrVqd4lDbdwK4JpN4Q24V7X2q2EgFEzoEEyA=,tag:vwFkA1HSoGf+Fng5YHyf7g==,type:str]
network_interface_name: ENC[AES256_GCM,data:9k0lnZdl,iv:uII4BA+oPtKpIc6EanVMs8+zZhD4XdN+biJkYZMTK6Q=,tag:wGTnl17Y9JgVCVJk2L89Fw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:47:56Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwG0RjKcQ4viqFU3V0mRNs/KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwiiraAL1oHLagQmEAgEQgDuZt58Sb9qHx4TYShyoOP7AbLJToINgjlh0r9vnvr1gzv4XrSGj9H/ABiTsuC3N14W9XTGM61toHd1pdg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc1dYMDd1RHdPT2hqRDFp
            WUZISXRnUnhna09IdDdlSFNKeWUyN2I1TWdJCkY3VHZ2WkJOaEZqbTBsMUJJY0Nj
            d1RTazNWTWp0clNOVUY2RVFxdXYxQXMKLS0tIFJxOFlCNElQaTRlWXNBK0U2aE9n
            SHA2TDAyNTA4bFRVMDVUdmZJQUc0d1kKVHUpyUQX1u9J/TPonUcHRpNXcSkPdO+t
            Uhtu197RughUybb1SrBRYbkjGZkasNlrjDsEUi5GxOHrr7QZi4covA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:47:57Z"
    mac: ENC[AES256_GCM,data:a417VSyBWD17wQFOXQXFvZxGPXX0DcpFPsd1cDVmOjyu9ljP3oXvfAW9XHwaMLHdJhwjaDVHvBVltbtoceGN7fhjDDLJfaPWO+2gzgZjWUIKXxyT1zkkdlo9j3DDo1gwHk50vjEHS1t/qdO17xjJWw/jRuMRaS+qKKQvLQC0+GI=,iv:UQqf/3y2y1Wg8ZC9UDGYcq4996liyLmwqTXoRDIUAT8=,tag:Er4CqZi0VVGNUUdSBcS23g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
