ansible_user: ENC[AES256_GCM,data:cnlNXI42zgrG2/5E,iv:dErWk73voc53VMjjsRHrIQiBTmJKawbdTZe7rxD7CIQ=,tag:hMZNcRqgT5PohAvHvZYmcQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:48:01Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwE1gpNtL3hd+TLtOHHDJI1aAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaBHyaZMop8hdr419AgEQgDsivpa1QUmTF1urTaNYkkk8j0VDu14+hg6l1RJjJvxyH0AFyqJc6UZMxS/KrokpsAuWwaMh0VLLxNqpww==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZjVqUFg2RElPZzRGSXlT
            YTRJRlVLNVQrdzQ5N25zc2lMTVJpR01RZ1ZRCjdsMmhQSkUyUEV3cXcrZkhTWTFV
            NHpXZTRSSFhkNW9TZ2V6eDh1bGk2SVUKLS0tIC80eHJYWnR5eVY4SUxHRnJZSmJO
            ZzBNV3dBVDkrWGl5dU01UGc2VkpvZncKN0SqB+hNbM7JDmWoGS7W4xkxzGiNTimS
            iHPkMdINXkgKLQaUP3zd7zw3xwVW3u2KDO/n4BcYP69AJj+RcrGG7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:48:03Z"
    mac: ENC[AES256_GCM,data:f0Y1gnZXiOFjElOou2VvBDaSbxcWc58iuvtVu/oTB+bhO31vgSCyd53/j5pZAH+pQarHHPkwIyHWH2Aooyc+0gjXlq0ZKktlzwfOjfsUTSww8deFqWUm0SQR+TDfMKnRmLOTJlOQUW3XLogL1RdyInqLl3850V+wi866AtkSOhI=,iv:dXiptI0qLlbkgLhnx5JX3zwHmAuU95GcJay8MWn9mE4=,tag:W3izoI24Ct305kxkDL6tBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
