ansible_user: ENC[AES256_GCM,data:a6sSrqOK,iv:Qa9/RfUSPqHOy8lWNCgQuEMmvSjFzcKGB7yLbw/QWec=,tag:nZMyjPYTH9HekHotwhCKTA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:uQSHfwWT/s3AwAIaY8qbaw==,iv:+A19+M6VUBl/zyulFZxrpIfiysk8ToPeW9coCNTRV5A=,tag:hyL8dcMshw9E0pbQA41k7Q==,type:str]
asdf_user: ENC[AES256_GCM,data:WrPhHPhl,iv:11gw9yauaDJV15PvEGFfwx6FXbW5U0q4jJH7rY9tU6Y=,tag:AUkEKPLsvFxHJ0x/yYjvJQ==,type:str]
asdf_shell: ENC[AES256_GCM,data:I8gA,iv:Eh5PnmRg+Pzff2ATdYhT2vNmLLf9+LVAGYF5Od0a0+w=,tag:2WG1IIv8Cp5Cr/DWGFocTg==,type:str]
asdf_plugins:
    - name: ENC[AES256_GCM,data:ndIHu9ca,iv:HzIkkefxnKw9U2qNwMynS+GDCV93dr5ACyM7+RxF7WQ=,tag:oAhGHF+4+iNerr9Qyd+UWw==,type:str]
      version: ENC[AES256_GCM,data:RoL87lFz,iv:35dwkUT0XkwhE+Ioa8ysOm1r/s64nDs1Uroy5NrgmOg=,tag:+vkDKNJUW3F3+EVCdpuVzQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:47:11Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEMhlYXpSbRtMYYQ5lRMAmQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkNJwQOFADBTgcNQcAgEQgDsLTyFTa3ZLx5QHzlZT3eBRJgYa33WxuNknoJ45STanrK3QQ6JA5f+2b+LOujQJqosiy36tUeQt/FDgiQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbkZ5bUdyVnNRWng0Wmcy
            STZTT29oRU1HakF2YXVNTHcrWDhEMzlDb2hnCkQvRzRMUzFnd2xncnZyNTNKWFpk
            NzV2UDVnVHR5dlErZ2xBOUNXamo4bEUKLS0tIDFNMTJNcmVCY2swM3pZWXg5eGs0
            RkE0WDNCSDBiUTk5OENGVnlQbU5rV3MKG0UNDzDvF0lWfmxiBXfHfI89ffSUk+Nm
            Vm97bxCmZpF9dIIt7a6F3PU5ERMSgq0CaFRVPkER5nkV8r0m+ayuyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:47:12Z"
    mac: ENC[AES256_GCM,data:aesoF4hVqrmxEWjrVDByOE3JoaIduPq40iy0FEZEt05CxHaNRLBh7B59DMcWmNpyV09hsa3xsRiLnQ/qIC0n7PoCRY3ffgxo8rMWvDit9tiWYK8ykYqveTxpP1VCbn4T1nTY2WXCqjFD8YFGRSwYWD8ibOuJHWjf7dYW94KRDtY=,iv:j/ubCyK010J0KDu7zRdXiyOcBSD0L5I+dHQSUo81+r4=,tag:iuzoK7rkr7sHQOdRaFvhEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
