ansible_host: ENC[AES256_GCM,data:SQVCLiPy3QwkYoANyqw=,iv:54VtxfRLxRT0H3Wl3CR5JJVg+Zvei+4oIO2Jxjp27l4=,tag:3FiaiVafEqRh832SSlkepA==,type:str]
ansible_user: ENC[AES256_GCM,data:ym38HWC6,iv:eHPVnciSddags5w+zblK+IE91stLHpdNt0MpsLdvLa8=,tag:qDO/WKMZgtioarZn+Kl/XA==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:11/w1ufU8iZZmw==,iv:TnozAqhd+1hmjwWjWJPd4lS/WMxAEwL0hVm7YD0Hxpg=,tag:v3lg7EbNc7r1Zxp+TLcSKA==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:7Iz7aJHwoSc0Ve0=,iv:8WadvlNuHvcsS0+HJHP6z5e+6cmrPjE14CfoMqZBW+o=,tag:g1fs35nYkuBxQe76UwmwJA==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:bchctyUaLRsHaaoWdCNBFErdho/QSZ44MdGc6KztlmjYgkTYOaxKq2OHKLg=,iv:oBNeuNpRkVpxjMIu8YXPmbN9WCWEj+21mEMQ9KhzNJk=,tag:i7tICOECEzx2FQp3FjPWJg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T21:31:17Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEwuE45Loa0FAr9hAstLyi7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMJ9N7JErDeMMdV4LrAgEQgDuH2rFlH4IHDSZNKsgkjCgZ1WaBnvx8kV9LEQHQleQvExbwu6oX7qdjJkfVqq2UolggOaNQa22W2xJbFQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZyt0clRzTGNiVGlnUlRl
            aXBMVGxsWHM4NHZkczIxZVJkclpaTmo4NFZFCkFxekdQdEhYYml2eHV0ZEN3Ym90
            bXBnaDl3UUx2UW5zcnFqYzBZZzRZZmMKLS0tIEV0ck0zNjJ4cnFWUUZTNEJuMW0w
            VGdlSXYzNzIyQ2Rmdjd0YmJINEM5aW8K6abLZd1n62i75shXDY440RPCphkU92Jt
            nKo7NWn/OMRMVfzcvDIxP7ruO0ye8oBUsS/Z+7SHsGfL8ZO2BVTDsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:31:19Z"
    mac: ENC[AES256_GCM,data:A3Vo5EY2dMNGt4EohrDhKJjWbPn41Ws84ssPRpSm90p2VsHJGbUpndnNXFV40Uboh1lhkL7Hn9u9hccV942+JEN5Yyj/9WkOiibqOi/oiSzQnks2jw5jIj+A7UgWVXzoG8iumcPeXeN52cdYo72xUdIsBeRuJmLsvnjm9J0Loto=,iv:0lf+fNXCipQ74qxD7TqkrLP9G7nt5jJVCbF9H8uHwME=,tag:bKmbirRmZyEG2k783mZeRw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
