ansible_host: ENC[AES256_GCM,data:P0aWQS/N3m1S+jotGMo=,iv:P8aahvvj8PnNONBp5p0qBHSV/91JD0MRJ2tCqnEMIko=,tag:BcG9sJTKIRwd73sgnpHivg==,type:str]
ansible_user: ENC[AES256_GCM,data:beeXODRc,iv:xMiEscfAw+aRXZ73dSCvvFc9YT1mlfbzW1mqosJa3Ms=,tag:2Bmc1kGftvJ8BFppspm/1w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5SF08Yeyn8voE9lhXAem3g==,iv:/PPidZp0n2V/Pc29YMT7qG7GF/eUS2xBdRmSTatfScI=,tag:EXFXiC85tuemPNZDcs6k4A==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:fjaTxFd8cXJWsw==,iv:fYY2faJzx9EEaBFOLE5QpGVyRYrAgiaezPQ+IGb4IVU=,tag:4vXVBT9vGOKgXi+WXOkbZw==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:1iGVy0Yfs0WiBtc=,iv:pY7NMRcRCQOmTVhKrb29OZ9KloqkzKt7NrpguNEa/oo=,tag:6ZvUm5SrBtu8FVqbUMRHvA==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:Sk95rV1q3rnyDA0ByKFokl5yfSQZ3ieEhdc8Rn8CI5+RLQMRF1GB+k8VY7A=,iv:A9wMbhc/m9jDpKOsr0/jMhW/vao+2t+2/YeKgrJqqso=,tag:RkB74upH5efHmHyjEdTQRQ==,type:str]
wireguard_dns: ENC[AES256_GCM,data:FYTs0YH8SZyFdQ==,iv:OBMN/Ne4zdlCYzKzgNhQJoFCgoO5B0lN6/IlEHCJJDY=,tag:DgZTk42SOO6y05YMLkzXXQ==,type:str]
wireguard_dns_domains:
    - ENC[AES256_GCM,data:yrll19k4bt2DFr+/NJYQz043v+zX2x0=,iv:elQRCqYVwTCGmkjoRVFNv6ZYNXgvZ1bhDW2IZ4o8LS4=,tag:VfEEAebLv/HJ/C0qWg+GyQ==,type:str]
    - ENC[AES256_GCM,data:P2bLAX/i1K3iqH9ZN5Dh+y6MsHf7,iv:nmq/JUcbbNcPZxG1NsdU0oQSDFZUvNSZnOClcPzyAqg=,tag:zj6kYIDAH2DjhrWFshJLAQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-18T21:09:27Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwHEzTWv+a0uv9weYuMSHW3PAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeeBc9pTsyncDOC6CAgEQgDuJ4Q4wSNgqcx7c0uQ9NLHUP1zhA5gNTXtw6OgxvmbWUnvs+pqsmXxXxGd1STboCpo69pNsCuL+ZgVYyQ==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTUJLV1FMSzlpdTE0WUhF
            by9FenR3V3RCOVF0S1Q1b3dGbDE2VzZYbzJFCjdCbHNaYXVVR1ZXc0RuTE9TN29Z
            N1AyUGxMc2UyeVR1YW5SZlVWTWdVVjgKLS0tIGVjTjVrdWlZa1FZVi83dHJEMTll
            TFlUNVlWK1ZETEhwaktGSnN2b3BJYUUKhFGdU6lQMKMKbCP3Lc+nzwirJExDCr36
            L6JvIrVyQYxDOmF8xP/wL67C/o4mKGELjsvk95lFTRZY256K/c+HyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:48:53Z"
    mac: ENC[AES256_GCM,data:I3Z1SWgGeonHaC1jtanaN4MRyY62ZAmyZxumzB/XAxc5BDuOYJrxJXQpbIpnW8pPVs5WpmzWT8dRWEW5iFqg+jgy7Xh3Do3bwTERKBkk/5h8L2FLdatfaJ7DFIHYfp9IOLXqwQaE8OthzoPy42DjBa/mUJSr1zIL3GoXv9vYbZw=,iv:6LpkMZncN+qo0G4eHgIQGCu3wrM1VwU+pX550b4AwHk=,tag:DXPciwlBHF+tEjbInlcDqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
