ansible_host: ENC[AES256_GCM,data:P0aWQS/N3m1S+jotGMo=,iv:P8aahvvj8PnNONBp5p0qBHSV/91JD0MRJ2tCqnEMIko=,tag:BcG9sJTKIRwd73sgnpHivg==,type:str]
ansible_user: ENC[AES256_GCM,data:beeXODRc,iv:xMiEscfAw+aRXZ73dSCvvFc9YT1mlfbzW1mqosJa3Ms=,tag:2Bmc1kGftvJ8BFppspm/1w==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:fjaTxFd8cXJWsw==,iv:fYY2faJzx9EEaBFOLE5QpGVyRYrAgiaezPQ+IGb4IVU=,tag:4vXVBT9vGOKgXi+WXOkbZw==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:1iGVy0Yfs0WiBtc=,iv:pY7NMRcRCQOmTVhKrb29OZ9KloqkzKt7NrpguNEa/oo=,tag:6ZvUm5SrBtu8FVqbUMRHvA==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:Sk95rV1q3rnyDA0ByKFokl5yfSQZ3ieEhdc8Rn8CI5+RLQMRF1GB+k8VY7A=,iv:A9wMbhc/m9jDpKOsr0/jMhW/vao+2t+2/YeKgrJqqso=,tag:RkB74upH5efHmHyjEdTQRQ==,type:str]
wireguard_dns: ENC[AES256_GCM,data:FYTs0YH8SZyFdQ==,iv:OBMN/Ne4zdlCYzKzgNhQJoFCgoO5B0lN6/IlEHCJJDY=,tag:DgZTk42SOO6y05YMLkzXXQ==,type:str]
wireguard_dns_domains:
    - ENC[AES256_GCM,data:yrll19k4bt2DFr+/NJYQz043v+zX2x0=,iv:elQRCqYVwTCGmkjoRVFNv6ZYNXgvZ1bhDW2IZ4o8LS4=,tag:VfEEAebLv/HJ/C0qWg+GyQ==,type:str]
    - ENC[AES256_GCM,data:P2bLAX/i1K3iqH9ZN5Dh+y6MsHf7,iv:nmq/JUcbbNcPZxG1NsdU0oQSDFZUvNSZnOClcPzyAqg=,tag:zj6kYIDAH2DjhrWFshJLAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUTdsc0ZZaUVPYjNabERU
            RDZvNFJLTUNuN0RwektXeDB5QU8xa2tka2xrCnVyZE9mdXpLOGRGRngyNkZtNEJa
            L0VmOW0wQVZjUEkwTWpQdjFXTHJGS00KLS0tIFJoYVIra2EvM1FMMTdRcUJTVlBF
            cUc2ZFFaeFNkUTd0QVpOWXUwN3k1V3cKCxpvmrxlbK6s2EVbP/tzi82OlSupSgn/
            getYjua3ibpRWlJQaNyRqPNz1CH7NcuWpgllH4Py6//yqZJqTZkN5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T18:11:32Z"
    mac: ENC[AES256_GCM,data:lRP3JYifmBv6GHYzZxvxXvOPU9IFE1xZGdIFrJznU+P7TIsnJf0LCNgJsn10k/DsDaowPyzNSI2Z7U99wENcGwnhRtsjmpzgvITxhiBFqi0DdgWoHanPBhj0fCMP2jnx01y9e0PC0De5JWFec+tVWh8MqvgEoohswaebWHPEfEc=,iv:2ZAPG5y/MuZEFC3teXX7i8FuPtN299cBu5kerBk42f8=,tag:C+hjrhMMqRVXLv7teXhP4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
