ansible_host: ENC[AES256_GCM,data:3iLiixMPrCbLxiROVNE=,iv:lbE5RoAA8DZljj5sNX35DvQjPEj4aXBbQ9riA2DD8sY=,tag:VIbbx2yECyqyiANtz6J0ow==,type:str]
ansible_user: ENC[AES256_GCM,data:daN05jH8,iv:eNyDBcKga7xwWrhCtnfFlBhZgSoSv04qgv1V886Am9s=,tag:3lk4tcydfNtDqNNVSCpmHg==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:PVjZaZ7fi4qVSw==,iv:IfvTOvVTV4wvMc5Cds/geIbrlQ3q71w6Ek5/vawb714=,tag:bGVsISw2B/WYXDne/fLwCw==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:A5DbxQ5J4sWRz5Q=,iv:xEMfjT2pHSduisrpNoxZ6+2l+el3SfYBY9GL+59lJmM=,tag:VQSWYFFy+GKKj7+6F5LeyA==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:Ei6V82nv5+szeScjTUZhfove+qtOh0aJZBSFLqVd8a30jml5HNLtvOQpa0U=,iv:919g/Cc9cCeRwDVZtrXLSRhglWN5szbN5r5I8ExuS2Y=,tag:LYH+ugspcJYuj9wp+/A3dw==,type:str]
wireguard_dns: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhayttVndIeSsyRzR5ZVFU
            eGl3Nm1QWGRVREhCSXhQd2FZaVZNOXVwUDFVCm45aVBUUjEzQWE5dFRIS3ZuWkVx
            KzRXZzEwZXBvMHYyeGlLeEhMaHZJWlEKLS0tIEVyOEtQM09Gd2U0TnVKR25lL2JY
            ZnpFZTdrbnVDd21ncEZpQU5iLzFpelEKVkbCTb2SW8Phd3Mo6+B+g4HBOJQda+gh
            w6hsYXCIfAlSRPuAJTKmXZhfIHlKBdZbuz0WpXK3nScbQhmLyhPK9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T17:56:36Z"
    mac: ENC[AES256_GCM,data:gE8JQvWaYMpiVbwqU+VysZSZXmZnwb/MwN9vJBtHFIY83KDL0wacmZkRNA/+UZWgZlcEOD+VqdHiZbXHtXVPhBOFKdMzn3hoH7ff6Hd9IrbjX9acdTjswqzEGDKS159aWKrtdg/6t0myGnYmNGUDl2BTAGZgPMD2g9vSknNuCno=,iv:FVEDAX+tvD9PGhC5z6FRCxxXoaxP3lm6vU3X+BvAt18=,tag:R/iFIk1s4paFMyOsVNCiig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
