ansible_host: ENC[AES256_GCM,data:Nw13Cgpe0tC9wEjEvno=,iv:A95nzkugaoMyXtByEoaCok4MdpsF/kMyEj3o6prOdBU=,tag:qvH8GAzdv2IKYiT+BgWbIg==,type:str]
ansible_user: ENC[AES256_GCM,data:i0/KCJHe,iv:pGgTSqe8JuAqWWlEuYS0ESKYop1VtKdt7PlFoB58G9M=,tag:g6OhLhjVH7ra43MdVZfCrg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:51:16Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwGrcNcBcMUC9bv+oYg9ro8NAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM77dnODpHBTWmDayoAgEQgDuDSJ6Z7BhDeSP3c110rfzJoAQPHBpexK5PaHopL244etUxDg8+/P829JpDQoEwHkUFPSFoshAqLZFL/w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMTRjcmxRRElraWpBMWsz
            R3o1SDBORjlkZU80NUJxMSsvUDNCc1pmK0FvCjlRSEhtVlRBc1dlYk9Oc3d0YURX
            cHhNUjJlV3JxZGN3VERJeEUzYmgyTVEKLS0tIE8wM2hQM0FRNUlsR1RRY0V0Mmw2
            U1BRN09jYTJyUWE5NjNrYzhQVW5mY0EKN2oDrS/oVdn+7gQWqa8tzjauKVcoYzG4
            dINUBRMtgnN23+sCBtGKS0xVn97kYlIwMdbC6E1I2TKB4YXXK+frmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:51:17Z"
    mac: ENC[AES256_GCM,data:iWGuLA8i2j7sps2nBwjxTYHHPQWQT5GPUeQFkOY/BaV3saLjkYMUrGcmjk7OFLp4wLvQs5fFXnf3qbAoDkxlr6umaxYXHn1cbVLDnAenBeN1Uaz+hY1p+w4slijbGU0Mv8MknxJzS04Gva8oqcnjNRYNOwu/b6z/BRjAUz9i64I=,iv:ngATf03ExsHNE1dTOkRqkOJza7giHeK0xkOOcVfFD3g=,tag:OjQowE1iFSz5Y+UiTdXwLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
