---
# Vector role handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Vector
  ansible.builtin.systemd:
    name: vector
    state: restarted

- name: Restart step-ca-renew
  ansible.builtin.systemd:
    name: step-ca-renew
    state: restarted
