ansible_user: ENC[AES256_GCM,data:IkhihR3IBtVgVEMe,iv:YdGc6ZBN+Mo4SO44N1i32q4hxgZn7C/vTlFJOY0iClA=,tag:mxcEKnZsymXgjgkh7xDUZw==,type:str]
custom_config_dir: ENC[AES256_GCM,data:isukeBjAUTW7SvyLwTDK7Asm/+E+R5YCEEI3HLGWid5BLtqNxWxh9FPfNJCd,iv:EFNMf07fKPXjg6LUmzdVw28aa1iuIgT1HdTGwJC47gg=,tag:hxT5yibvOywo/SxOoas4yw==,type:str]
custom_data_dir: ENC[AES256_GCM,data:yMuX+0oACGb8EYfCcNiMWBkIWqEOGF/sMnjfqFX/N4pDfZcpusP3qfiORQ==,iv:R7yW9EQPjmyva4ZsO8xjMdrUVSUjk1JF3NNaSFqM/7g=,tag:ti+jBuF+6656CXus/3UKqg==,type:str]
docker_install_compose: ENC[AES256_GCM,data:eSFbZg==,iv:8L+PTshte9AH3wLqSJKuMYCT3M1umu4LDFy13V6MStk=,tag:LdiIrCkaGf6WEKsS/9iIQw==,type:bool]
docker_users:
    - ENC[AES256_GCM,data:T5MknHlr,iv:S3HmhcLPClPl4z5GuZmdXvAS4RXLYUoELAbx81POhRM=,tag:OFcaUV+na0NuJORlKMfIrA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:52:37Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwHZVrpVYkFsqFCWoSLdVy5bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrH2QfNdxEg7c3qLWAgEQgDu2rkhNxjcieH0Md8HPp8jHCZszwvqsUn/xA5spsDH/CgifxrGxzwyT3L+xceuZiCYobPnNYLv9hryLKg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdWVsakk2RGppSkFxMFpS
            WC9OYVBUYktiWkRiYmpCL2hZZzc5bUhKakJNCm45Ly9Say9DaXNZMEhycVVycXR5
            aVptUDRsdlowUjhwcnBTdTE3WTZCS0EKLS0tIEQ1RS8zaWZGYUo2K0h6Y2VsSU1x
            akdyRzJBdzFlOThtdW5YRUFNWkgrUGcKLWuH1t7cavY5AViUIEqd75hTfSjnT4Xx
            WLk6FrOhQm5pfttDwRO7GPqc3cUgldnMUJkUPCRR5tdHCnbM/rhNHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:52:38Z"
    mac: ENC[AES256_GCM,data:tT3ont6TeRHCv8w9Nu5fVkeL10BmGipRUWLBO2WzUgIJvlhIprcxDPKOW/WCm3/sH5pG11BGktjgbiE0N2nA2DfKchnTdRqFB2oRcyIjEI7oGZpYdd41ZA/zSxZGyzWHKmn8r2YKVUtqvO/+LYuXlm3PJPs7aLzmK/62vlddGKU=,iv:fvTZoZHm+ji6Y22qeK+r8F4tVDx9+/Jq9ZBInNfLOgk=,tag:LnWUOT0WkCnW9TBBVeDFkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
