#ENC[AES256_GCM,data:H3OdM7OlKggxBZ6d7S8tzW38l1Qlfc01,iv:ylTmo6EqUiD6hua+RVuV1UD/9I8OnqORSifEp06RZY4=,tag:nz2zoQsv+XZdvJ9YQyU2sA==,type:comment]
ansible_user: ENC[AES256_GCM,data:zWD8f371,iv:MSq0Y81hARRtvStDQoo6xeBUQdCy0YKeg4NqCfJxInw=,tag:HegJYwiRu3ey4AgS4pThkg==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:s45Fw3hBQdhvSw==,iv:41q42HBj/5y4SHsL8jbcLisp2QoCFWZIHY0tdrMoPMM=,tag:ABojyp5nONCOAEbEqMCZQQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-30T19:17:13Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwGFSWyYrn1TXdbY/ZiZUZ8NAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjDT4TIvDROLHt1+uAgEQgDvGIBR2XDJxH6H6Ew9cZ25n/Kvx70CA0PnVlYwMr7ZWauiQwk1j6S4TsEsEojr80BqfgQZQgnT/ih5hqQ==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWnJUc2lJV2R2SzVoN3Fu
            eUtyMklEYzNTWW1YQWtwYTlna2FTOXFpbVdnCnovMmVUN2pOYTF1OE0wU04xNXlF
            ODhnTFJ3NlVvUWFpakxvRjh0aWNLMk0KLS0tICtPVkRpOXQ5SVorTUZ3WlU4ZHcx
            aldqMllCUGQ1UkYraVJMb1VZdm5LaWMKPdF6ItDPERJn0tbbQUUIamKNhEpyQnC6
            SfBGPqe2d3HKCawP+FnkxrS+aalL7xhrxwJiGdNUa6sP7s5SdpicCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T19:17:14Z"
    mac: ENC[AES256_GCM,data:fB6u9v4wiZQTRmhZA1QD1EGVmxP6r+LcjIqa/H8umfUQxdp2P4h73nwrli9jO5XDAUpNSSfQKwgXH095m+AYcfiZvFF9wdP6jKMsb4NLeqe6xZCKfXVu2vmuuwI3qOS02KfJqo+SgqMOLMWCQYjr0TYms2LCEjRGgDDm5m3Qc2Y=,iv:woIR5uQES/y261iS7rWO6+uq7hVlRlYE8I5Bbt027C0=,tag:OZOki3+t0mWptPhqBfPeRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
