#ENC[AES256_GCM,data:Kr8iKkmAEw0xftv0ieF2jQwiasuFIwqGF1lKRV5ZCwb2+qUBUsIl6I+QUyEj6dLHxJ4XJBXo,iv:iCVgMzW+MW1jKbBSbROxaDMLUROv6IAM5NY/zHOtQiE=,tag:gzDLlDRo4uWc2I/otm1zcQ==,type:comment]
vector_step_ca_provisioner_password: ENC[AES256_GCM,data:9lZchvYDFYuELIwLabnQhIvHU8wFrA==,iv:3S9/UGnUkE9wYlkARjCybCgkwrRK/n7AHMaIHeDjaKw=,tag:I6NgQfsru/KTcd86/fXEcg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-22T20:41:05Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwFUJDuKxTdk5UmRvZjiduicAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM8wfupuQm6ZCUE0aBAgEQgDucYRd4JqEYlEv4bm0lqSo7f/am63/cDVJXMjxrdQ85WTIq3sr8K5kxK0+XDfYVqu9LBCRvK27ldM11PA==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VkNZeGlYM2E5SURDT2Jo
            VVlYL0VFY0ZPUWpRVTFvVzE3YmQvQWJzQ0V3CnlFTEJoZWFwWi9UUHlGWlppMk1E
            akZaVFNOTEl2NGdCR09hWUVZaVRlQ28KLS0tIHY5Qm9Camp6UlhXa1RqNDB0NUNQ
            c2lYbDM0RW15MTBaeXdUWFJqa0hQdGMKFGLiswZcwMC0NdOLdoazQQn+Mcv6c2vK
            CaiRROo7//ri6RO4MizhjUdQMFhtkJtBAGvtISPJ1gF804U1Ia9G8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T20:41:06Z"
    mac: ENC[AES256_GCM,data:oR3QdKKPfv/Dp8IA3w5G1uNFeB2uGlWGyul7Lvl97tnzaoOgIQkBsDni+B+QF/4EQjZhKfkBtsZSL3LEe0OR9Ff/1ggdSCQPDSG4zA5Nr/dnLay252gFYHfNW1zqA4gI7zogaRvbc3eaFxUzkJ4eP+eUhzhkbhpSAi3+GCYAbyQ=,iv:BKWdDUmUjmnDiO2rc72zDoGbkO6fRXFnYKWSQrd40bE=,tag:jMiwPGmkZU3NJh8DxUk5lA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
