desktop_wireguard_pubkey: ENC[AES256_GCM,data:7+inw9Boe99Raphm0h6akTTvIfpvTfpP9sHKYsZ8jtRLgPncDDqFxuKYq8c=,iv:uXROkifQ9Ba1gi42OGXctByOBqo0GKP0N+jpZdHOBL8=,tag:kTlUiXL4iU2DfxvJ+gQhxA==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:11Tl7UGIfQJpiwFm8op8tmf9sCWWc7p5pzzncjegTNEUthVzvsqxUp9RR38=,iv:odCzaxQ/65sDbdDNTxPhMnIViqqzRh4uoAXiQFoX34E=,tag:HtLV3dCeRS8+dNp9q9CGiQ==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:Y2zxiqOgEP1VcjYBFolG8KlqgZMt2nKXRwW2HSaAEE8mevOg+VXPmrY5dJw=,iv:IEFNaAm2X5XbOW0F1KOFdJhAsm245FdsLlEPhBsfCFk=,tag:Dex0C5BmK38ptRA9xUdIew==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:XhTsjw+vOm0Pdx5mdiFkB59y96PHXptyOo4uNRdyn/TKTlr3N7ixPTQPgLs=,iv:ixUa8pOV9BZ/H1gEfw/s+YZ1lIRXGwSuYbJmS02g9pA=,tag:xqJZEZzUaxT341H8ZPQOhg==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:y0hHBYJaBSbtsteNlQlvN+T5miiw7IfFV7JAqBGKJI/1fM9lXB2fkE/ACQ4=,iv:+bU2kK8gRkDL1hLAqn0/YtlYfdaNu3kXyCwO60/C6qI=,tag:0Y/rGDIEvieZ4QWssusJbw==,type:str]
mouse_wireguard_pubkey: ENC[AES256_GCM,data:UN1zUHmKzGGXBuTHm/PRmRHlC9HGGa2NAjh9MuQImSA3QAyeCklJl8wOSss=,iv:/Bp0St4EKJAB6YHPdZVDqhG33Uijn/u3GAsHhEMBmHQ=,tag:BNnEYtW4G8pxCvIU5oQlZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdEY1bjRyb3VUZHhwTlNI
            LzRjUFBqV2JFRWozWm90LzNxck1ZQzRKM0VvCmhwK0NqczZ1TVJFWVI3MHZ5WHJJ
            NkdSTmhHV0VnSU1iNzZtd1hpVk5aMXcKLS0tIEVyVzYraXRhb21td01BWHNVeG1w
            OGJDa3ROV3Z0ckR1amdMMklFZG5aaXcKfnLdjSqddxyZ6SFLxe+d/hOS5c9vbzSI
            wUuO0IbFaD8qtB+rgVo11gHdwupdNmQ3iRaQyb0CXOjTZdYBR9TxOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:49:02Z"
    mac: ENC[AES256_GCM,data:E9B0fIKKPzCPa8Vpepm+tAk3BI0lXR13N/lsfoWQfwW9QJkvcEklJVF+yRAVS0NQJos7hBLP2EHk6ufmKpzSGLWsHTP6O5E0GE6oBvPm42oKD3k02OkQLgQE82apdXLsYR3gPzn3cpnhgegoYa1p7dkyLt147CXKboPnK4yGdgI=,iv:UwVeV8NN+oO66EUZPMJsqUTvLFKON3ZTPbA3PM/FNSA=,tag:DDe+/9plcKEmSR6KOy24RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
