desktop_wireguard_pubkey: ENC[AES256_GCM,data:sMLrfdVnrLu8B1KjRwlt4M3LNLuX/OzoC1pD3lFXhQqS6IBGk54KBb1uVBw=,iv:cQopGj2CGa+V1PJZV+FaoRN4UkCstmCtNQAOJMlZkL0=,tag:NgpG+PONG8Muf+Re3TsF/Q==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:PxDD2zqEFen08iBUgto40X7EvNYAjqv+iTDFoyjdSVgA4IilyhIn+xNTcOw=,iv:i0Fi9YuxyH5hJ43AsTec2HoWb9aWMsONKqhHQX/eQu0=,tag:4XGXM8KjEN//gEK18QOoUg==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:2EIAuRoQZC3AOLEafT9YKjpGAw6/uRFyn+wdWmk6fzbbGG7eOcPmS3D48iM=,iv:/u/cfkwi4yZ01okfNBS2J55fU46L0fPeeB11h0Z0r5E=,tag:rAsmwdYSql4GQhdBDwEqHw==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:AjjxflqzLzTuClxT7mVMEt6UpB0JVbzmW/a6HtyqUlLP5I0jnMqpjtqiSQw=,iv:R4vvMmoVU4rAd9JCSFAY0hp+BDs0JFiBrDDEh9I36Rk=,tag:IfVTTnBIU3fqej1jFE9t3Q==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:awAB+aYVqoMhhU1Udm6e9GpMmXdRYhTttkbho1IYI3OemXCgoqgSq+4dwi4=,iv:nmsAPieA7Ewv+WE0aPzOKbUh6yLg3oYYSKJKI5cL+gs=,tag:Zuz5RUsZd0kLvV9m2VQ/Hw==,type:str]
mouse_wireguard_pubkey: ENC[AES256_GCM,data:nF8OYwCLS8tTvQqWSrEv/MmIzQ/Sfmq98F7wXqGYq/pjP3nZ1fMLj9ZZxEQ=,iv:NqEBJK3EXi7JKKuJrnWehX0ObPUfeUZgOAfKifiqWZU=,tag:nwbUs9zCj858btttVfNlBw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-18T21:08:45Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEDHqIb8r93hPYmIzJ/aoKqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPMxzTyslr4KXPEszAgEQgDsuG65g/YOVZRyLOpAsI9f1lsEXhbF7YvwT78paNLkrDFNlZGtKJ1xpwiJCmlllwvc9dk10kOYA+x8CYQ==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTN1dqNTlhUlB5eXNJUG1F
            VnlrQ24yZCtIYjZQOUJFZ0ViNmFJWUZaaG40CmF6ZXphTFp1YlF4RXNjV29nMHBy
            L29Eam9JSEJQMHpGdnNuMnhiWmxoNWMKLS0tIEp6a0xEKzNqTU9UcUw3RUQwVEhI
            aEM0M1MvTkFFTEhWTit6ckttejRibHMK7ETg9LJF5B3nz3uRZyM6yQvfMgCIW1gf
            pHwvAynyC37zPiZhuXP3Ff6x3iHAt//Nt79i8blz5cGFA67zPX+BoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T20:53:29Z"
    mac: ENC[AES256_GCM,data:RnOxKZmymKMeCHiPkBnYHJIQvOhKFq3fEbQYRYZcuq5GW0sYs9bD4G5zhTEWf/pnFMLbd/93Y4kOIUaPJR4xMs8gMbT8KNh5XQr9VglcVS7aUwUxmFAIF6gx9axbIJimVOHf8uLBE0dPpD0rKQB6xa9PuGLNmok3F/4g0TmOvvI=,iv:4x0LFByYPj9NkHTerrf7l4UVovaKH02URMlnhOD29l0=,tag:Vxrbz+pPebkNFxvJkmfVVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
