desktop_wireguard_pubkey: ENC[AES256_GCM,data:QhNfkYQ17HWpGMW8iA9r3eLhy6poqlBskkig015SZT4eJygagjyyDP4KkxM=,iv:1Zx2FFfATKrLxiGqiZljSn/Gs33EuSGnngdzLC/QKdA=,tag:uVdi8cZb6rmPihYCgLgxlQ==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:lRjCxX18Oi+GN7+lKJG/5Y266lXove+BgpqPTn7kGccHNrbbB11DrP8FfQw=,iv:VJ4xMl0gFRyTPsCNa8/rbNO6YUiBfExVJo+0Pu+thyM=,tag:M/hSGPNxCOpnKe9ql5u1vA==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:/MarLVtH+LnQYKH5+EC1SWTS1gh1LZW248h2WSrsh3FTp84DjsLPzkntV6w=,iv:QQ/k0/h8qpQb3gku77ZZbcPQUA7txuxHy3VQM8YVOAM=,tag:pAU/kVukpI3SmlMClAdKVA==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:2ofnUp0j8o9VlJMEOG2eDsiMBbOHAgm1mnRlsJP5qiNSUORCRriArBIZQT8=,iv:asBBBY6CTzRaFQGs0Cpj6IwUCysKH3bTqvm0fBH2NuM=,tag:E4AoPdgyQfc3BXDyZjfnVA==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:kt/Mytogo7T3QIWdO+dMww3RMM7W5+3/qd50KNV+UVYlFCGbp1LvoJeWeIs=,iv:84za5+zg5aixUZ1BG5jdLoBpvi0d5yGhQigy12+89z4=,tag:DvLfw1vnNMZ4l5CCEbGCpA==,type:str]
mouse_wireguard_pubkey: ENC[AES256_GCM,data:P7xxlyi1VDkwYYMYz4AjDLmDtWz5Jzd3/CH3I2vq12yySYzXdxt7Ckjo9RI=,iv:A/FAD34zJk+rnmA4Ovl/b7XfBOPOQCu+1MZ6YbEDCRU=,tag:c4UPYI+W8pT+/NSbX2SlVg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T21:30:19Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwFTu9u/FsG/Ci8YmjaDToBkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2lEHJOgzxox15j6hAgEQgDvxEiS9OqNWsai9npUAv70lgp9+girHTDHC82XbcMgGx7XAaWu7bizX4v73FI1zpP2bYkib80KZ1GUJKw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZkxMUlVMN2dZMm5vNVRE
            dUNvWkMzdEoySFk1N3QrT1N0S29aSllFNWs4CmJoYjE0Sm40b2Z3U1l5U2dlb25X
            SkVFOFVsTjlNRmJEZ3U2OVNrZ1piQzQKLS0tIG8za0FzaDFiUHhhZGViamRTby9o
            QlR2Q1liR1NpRVh1Y0pCL3NtQTNVb2cKaqyMRsZ+4qdykqZ8ZJCjEcpzDlAnH6gc
            s/tbFmmtOh/XgzO7zB78a4olvHnjnsoP2VMdHV/prt47uOkdKSw2ZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:30:20Z"
    mac: ENC[AES256_GCM,data:fFCfibtlldTIDxfKtSUCJ9rugEY6zC9/QwzsTLixwEe+ni5FVlrvofVzY5Bzh/AFyQgC73r/wG8B4njkCxru7rroUhfatsijSG9yyfahDrXq/Z/JOkMnzNpBTrThsHYq8GzkBGQ4mHn7ZnPpKmhXvzHcAW9zucAkQp/4Ux+b5Ws=,iv:cDhgj/a4ufZz+oLGFIg031TnpkjJU4OSD3T1JOJhz0U=,tag:vC70JQeNd3wRifKu89LGhQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
