desktop_wireguard_pubkey: ENC[AES256_GCM,data:2UhAdhcZVPRHRoyaPLavTapXeHfZKc6fKA0cJ5KJ6Luow4tPD5HyYI47RiE=,iv:iwS5MpoiQjhMdQDrcTjYDi08S2IKeMymmquPYQ/0Ges=,tag:GgprY7CMMGuM2xu0kygZVw==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:NetJoU3w7DWM8oEvXx3I349a3KIf2CXpsechRUmwT/v7LmtXYV1RWc/rnU0=,iv:NScK/DkxIdxGeksY+3BLwn+yPIVhtcHJTnvBgQHiRDU=,tag:88GeZU8WRBGuaGHZ4WGZyg==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:o2z6PVcM6AiYZ5JIxwfQzLqsd9pSlktLcdwVMgyMve1bOyRtWULKgyC+HJM=,iv:XltW2KpA+y5pQuoWXh4XPkxzhEeUWmg26stoTwkniRk=,tag:QLSAROKic0lvJbXNi92vLw==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:Mhp5gzVMahUdOqgBbjO5UAPZwqsDWJPw+UfDmeRxuQKQc4md+v8AH5BmbKU=,iv:NW6SosASLmhRPEhUTcUFsFgpCzqD4oAupZ1VT4qyOcc=,tag:I8lG2+9dybL8mTZaZ3xnkg==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:lf7x4dCo1B0WlDrKf5ixBpjnIOzZLLIDEKUiIO7iDIWhN2v3pmn2NtFi7lI=,iv:nWi5dGqRW+lIKjA77V2dMbHFXDsmXwF9ISDLkapa+A4=,tag:wCuYmKJjblXcUsMtsv/6cw==,type:str]
mouse_wireguard_pubkey: ENC[AES256_GCM,data:uNyVM45ksoUSpjyut+PenTqt0wAuvlUSSXUlj/mn7HyOBNyxTg+8CdHmBrI=,iv:NDtlRQEJtQ4TSqqeOcj0Tmc05uNWI9Ep3jyPf25aFTs=,tag:RHGdXJK5mK2AkccJ5OsnUQ==,type:str]
oci_vmetrics_wireguard_pubkey: ENC[AES256_GCM,data:AD0OTnFU1jCYmPfy5rWmiOC9ioIPCOTHGKedPsoo2hR5idCPXTvcNmOeYKQ=,iv:ZALVAR4k+pd5X5eA9uSLDkx1WYWsm0QxwOzfl4vYkeY=,tag:0FM+0Gtj5jIO5s2ILGBdRA==,type:str]
rpi4_devbox_wireguard_pubkey: ENC[AES256_GCM,data:iMm51c7JhiyFsCaAIJnz5UDVOfdJYjHFviVcd5vf121yD2AYoDzPXhIVKM4=,iv:KDys1jge1yGtqXdB/khsJhytIsXnYGYt4+CpP9Wc6VA=,tag:G0/i89ob9WtXXtcWwljjRA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-30T21:16:36Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwE/Kcm0jadUBD3XtJVKhSviAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRJBJhyVyYArxkf8oAgEQgDtK2+ATlS1QpBX9HQKstsSd/YQ0Kb/DoTdCeBRVCEr54N/+AAQI2g3B0UbORawrdnlzNVaj+utMPgAklQ==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISG5TN1FNVFZUUTRLbFFi
            V1pxTzBPRDVBbUl3d3Y4emk5cFZseEJMZmk4CkVlVzFxcDd1WGhBWElyNkFzWHhw
            TmhzbUNVTXNTMmh2SnZpMWhPajZHSU0KLS0tIDFlNUFhZnBoSGI4OVg2SEM5enJY
            eXpHclZCMXFiQmVabVpmeFowNWhTQmcKOgGahPfrdyPIcMCdKlLI61Q/gU+6HPr7
            kAxtGj4/s+jBL2fVqxImfIh6cqMbN9vxiaD6u84HdGN2VcQVStBYkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T21:16:37Z"
    mac: ENC[AES256_GCM,data:ZDT4bGHF8nRiEAsh8N2MQxgr0P6UfPSo2l/pkgUP5EU/c1sl5WpQq4yltaAgIXsE2syvwdlv6Whs5ojPEQ0gpmrwMeBUKkBBLMZNA5THYaYiGYMPqACycOpHwDvGbEJFxzuQ1pQVnY6+t7qK91YoPY9/bb3nKczgd7W9zph63AM=,iv:KZ+eQkjUd8ePmfaYNYvukpksi7CWU+ytm05VTDhX/7s=,tag:ycDof9ihG+6R7szV6FqkFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
