desktop_wireguard_pubkey: ENC[AES256_GCM,data:09w3LsiK2DFC9o22WEpawPE7Gn6gbn78+BmbYpRNPv2pZABX6gMGzuRHkvU=,iv:WZq5bb3xtzvQPnjyi1kpbeMCk16iIbmqesy/MB4x+ak=,tag:ZfpovBzdOmbKsmJS72V5Og==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:vOLr73jLwxf/wLv06PKg+szzHJ4zJs+6ktw0gJG4EHH5C3MM3Umc0S2nIjQ=,iv:IBdoiXMqnlwvNN0eCp1a9p7MVTleosSOG9qU3f95uhs=,tag:xnofEfGPIBzYOFt9IbeY3g==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:Tj/ONE3Fj5Z4IS5hdlbM7dY9ui/r9GT1QbzYjouvJ+AAuWyI66FXOkSv+/o=,iv:91fhIsErZ/MkHBbwyiIDZ6omZvz2VJPQQ1tmnaHn5Hc=,tag:iCapvf3QU6s/gs5yqJsJ3A==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:O3BFpGBfEIbY8Rb4rQIV0uJ1ozYtOnYg+/hWaPQ0yd9kwkTN8s2InzvuyXk=,iv:UnukEDWnquxg7v9sFgTQRpvqQxHzmlzn4m9Lmz4Z654=,tag:Zg12VNDZArX62/PgO3HSCw==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:aGo+YKBc3sA8YWW+Zeh9CoIwmtfErPGq/khecXCdHk+ic9I0mvaj7eTrrp4=,iv:d9ukmoIAe1Kl80fyrAMb+Uxyn54CLu0HjLvY1vq/JWk=,tag:gIYUBk9qx8en6PorFc+bNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:45:51Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwG6JfucYIl5ClDw2rwuQIVOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5tYl4ES6NLL24UpLAgEQgDsYsOZUsXjkAFL18D0qfMnCqSoxxCkEwF6Fz/YtBjUo6cfzFLST/jQTGt0LfS0DfHBYnnppZTEq7sGeqA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUi8waEtzdjNRSTB5Njhw
            REp0d3lDdG9heERNOHkrNlRSZEpLMnVtaUFJCk05cStoMU5PYjFsN2xZMVRvNmgz
            ZGVzbENvZXFMVmtPOWR6ekQ5QS9JTzQKLS0tIGtRM3hoWThqRXNRVXBWQkwyUkRu
            SDVTTm5DeWt6cHI2eTRwUUk5aStUTHcKWog9o70tZQwQPvNcZkw9D+lSBoBC0Mi6
            ccXgv1xpW0BIoLaZzbq3DgnZgtPY36e3K+MLdxNtj7Y44Seg89pHpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:45:53Z"
    mac: ENC[AES256_GCM,data:8fR4+Hv/MDoRnxHqCqJlsrWmiZqA6twLOWTlTSurvEdDbHcJeQcjBkaTea4YdqX1kvBEuuyFsyMxKFnfb4gbHErnkPJjQVBtxdC7Vxivz+TEzknhNusheMoMinqBgVPiotsLzg32WktrnXG4fJRK7TtPvZqG+n8738jTnhZcmHk=,iv:KZ56VsB5aTHymEaSDHGlcTTJvLUH4wIf2YGmP/hUSI0=,tag:XqWaGeZhjk77q3s5rrPOqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
