desktop_wireguard_pubkey: ENC[AES256_GCM,data:sMLrfdVnrLu8B1KjRwlt4M3LNLuX/OzoC1pD3lFXhQqS6IBGk54KBb1uVBw=,iv:cQopGj2CGa+V1PJZV+FaoRN4UkCstmCtNQAOJMlZkL0=,tag:NgpG+PONG8Muf+Re3TsF/Q==,type:str]
rpi_wireguard_pubkey: ENC[AES256_GCM,data:PxDD2zqEFen08iBUgto40X7EvNYAjqv+iTDFoyjdSVgA4IilyhIn+xNTcOw=,iv:i0Fi9YuxyH5hJ43AsTec2HoWb9aWMsONKqhHQX/eQu0=,tag:4XGXM8KjEN//gEK18QOoUg==,type:str]
phone_wireguard_pubkey: ENC[AES256_GCM,data:2EIAuRoQZC3AOLEafT9YKjpGAw6/uRFyn+wdWmk6fzbbGG7eOcPmS3D48iM=,iv:/u/cfkwi4yZ01okfNBS2J55fU46L0fPeeB11h0Z0r5E=,tag:rAsmwdYSql4GQhdBDwEqHw==,type:str]
asus_tuf_wireguard_pubkey: ENC[AES256_GCM,data:AjjxflqzLzTuClxT7mVMEt6UpB0JVbzmW/a6HtyqUlLP5I0jnMqpjtqiSQw=,iv:R4vvMmoVU4rAd9JCSFAY0hp+BDs0JFiBrDDEh9I36Rk=,tag:IfVTTnBIU3fqej1jFE9t3Q==,type:str]
omarchy_pc_do_b_wireguard_pubkey: ENC[AES256_GCM,data:awAB+aYVqoMhhU1Udm6e9GpMmXdRYhTttkbho1IYI3OemXCgoqgSq+4dwi4=,iv:nmsAPieA7Ewv+WE0aPzOKbUh6yLg3oYYSKJKI5cL+gs=,tag:Zuz5RUsZd0kLvV9m2VQ/Hw==,type:str]
mouse_wireguard_pubkey: ENC[AES256_GCM,data:rIUZTg2+JB/mOWhsLEr22YULd2wLTR8WKx29TZjMghBSdv8hkFX3mHy7TB4=,iv:Lwmdr7YvKNL9RRlEOZ0f0JKIKuf1lQcXep98stNgEgA=,tag:KgYKExbIE80NnBQRhmx52w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVWMzLzI3aGxPZWwzLzJL
            RHVpTXVNK0VMTDJjd2RjN3pyV2M1d21ZWW0wClVuWm8yVGc4TGoybncwNU5kcmxt
            NGZJNXhCZ1hNbjlNT2IwcUdjTGNGdkEKLS0tIGNFUTJlV3FvZzNsZHFwVTFJdUFt
            NVZMNmpKdUZvRGtyeEUxM0M4R1BOWjQKsf5ijVnYBnKpo2Ta3XepErGamufLM8Ur
            jePMeME2MTyFfRWb3PyznngjB8QcsYlE9XgT+RXDBbeZK3Xm9ksP+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T18:20:14Z"
    mac: ENC[AES256_GCM,data:UXxSaU7iBx7/u+SiDNQt2LzDgGau9ZS9N+KblFP6kFMyNm9+BsyF/GIhGRxBJCDNwzmVMHcrBwO566kaRE0OBmDXuZJXTUf+K92O2QuoYMfslPo+t+9XpSL7wD4Lo59GFbqFiIDNeKkukJ6gPeBfmj+iwzcbQEgukY5h/RDx1Bo=,iv:W21JJXFI+dkPaSNMF7k8hDpki8AcVCDZeeZrOY+yh6s=,tag:rLRhTmvWAhHjv/oPG9VmPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
