ansible_user: ENC[AES256_GCM,data:/irDhy3H,iv:jM5eZ0NA7iaaxTFMlRGKXKJU7/9AcLvdUo00MSPbdWo=,tag:iK+7Y9DZ+sHzsUKaqdPs2g==,type:str]
ansible_host: ENC[AES256_GCM,data:zmgPXrBzycMq1011,iv:iJDhu0ZcxiYfzL3K47rkjkwUAcb4lyo5PhBwK7FKlFY=,tag:a6u+c1NG+5bVJLBLtEOOtw==,type:str]
wired_static_ip: ENC[AES256_GCM,data:iI1igM8O+Ho1reTZZkw7,iv:ZFJ4EOgRw6KDKFSvBVH3l1QAUEWo1jfyrjxvxKHINOg=,tag:q6//G0rPptQ7jhQlzkpfPg==,type:str]
wifi_ssid: ENC[AES256_GCM,data:Q94ZYDJ4/Yg=,iv:gvkLZw6/dSITnj20B6yVc2vXUc8t3KLaB5cIuq4z8sM=,tag:HHtDRq68snzl2EmqKRFaGQ==,type:str]
wifi_password: ENC[AES256_GCM,data:yYCDdBb7JgZJRCo9tI6zZA==,iv:PQuTNojeACS7i6mtOCGZkJOVWMUDzIjW2jdymU4YMYM=,tag:orcmRMfXr+VRh/vcwsxuvw==,type:str]
wifi_static_ip: ENC[AES256_GCM,data:t7xCeajQ2yyn5gvxslJQ,iv:Ez2PRAsG1LZ2gCDV/n1e+lVYfI9blELpuOFC63MZZKk=,tag:hEAoyQdPdw+0Sbtf3JWfGw==,type:str]
wifi_country: ENC[AES256_GCM,data:vd8=,iv:wdjKF447PLzv00PL8bzPRL3FJoNN2Czrg95NbyqyUCc=,tag:+rUNh98yYt844Dm1HQ3Ojg==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:HgEqhQg3yzq9MMs=,iv:Lygci36noMTl13mC0EHQ0rNuD1iC02Lg6zQxTZp6Tmc=,tag:kxqI5t5nyaav1LoHqHAtQg==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:N5xyyOHpv6zrlmXmOpGYXXEhZP6GT6K4OE2GlYVoFfeSQ2bgmkQlQZwuXgg=,iv:YXt/QhYNB/J6aHpahjP8QlqQC20NaiiRd4MxJuZMjqU=,tag:zrMDYQdgx8pqLGeOhDGbgQ==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:zo9ch6Ipe0qTXw==,iv:hp25CarL6JGPCkZnnHEFyCnYSPv3ND41qwQ2gfPFgZM=,tag:fIDwwX4B4Gqqbd/1fkY+Ug==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:52:28Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwHSykv/NQ7JBuYGxTOqrc2MAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcfZ9h/6BVFyevsQsAgEQgDuYutNXB+6ylZDEfdYzD1pgT3Z2cusfWBprz5cjauMmuU5sESbMMFuOcJ1dKf02QJ91hWleVEpE+wf3FA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSXgrY3RRU1F2UTVIN2lk
            UWYyM0syM1JOaVRDdDF4SHBSeFo0SkhUZEV3CnRnOGhjRWMwSGFvYmlNQWlnUU9K
            SG8vNjNjdjJydGVHbG5TaE1JTTdrbHcKLS0tIDlJZm91RUErMUx2UThRWDc2anIx
            VG94dmNweG41UWlXWUlNT1VnWGV2UlEK9z+ZDOkhyFoiV/S13RSUojT5yg8+9MN0
            zVRDGz7dwmCTIUxGbSgj2V9O6Wc+68JpkH2KU1ehjAuLi5oNAykquw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:52:29Z"
    mac: ENC[AES256_GCM,data:U3/XUQXO7faqRhjUD+0PH0AJ/Vt1YQp8hD343uIpDjJ75Sk2L8H3LdGzR8FgxgDY+Mx2T6jLcb/19xK12XtnxgV7u9PRzYv1SmSshiu+HGgXBIB37bMI8hKIjsHvn4uanRibgECAbnor/DoVN2AKXD1rl2VT9NEBMWECbAv2t/Y=,iv:K7nQSl9YJljaMTzEWKHQKqGESv56EkN86Qjj7R5DQ5E=,tag:FzbyNJh6IXOJ3RuSNznRUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
