ansible_user: ENC[AES256_GCM,data:Hk1yaaQ=,iv:zJl82e2O8L4GHgipP7klm/xl1mjJsoDhovZdkgQsiuw=,tag:8I8P4KVo/Bhz82esgOogMA==,type:str]
docker_install_compose: ENC[AES256_GCM,data:dVvdsA==,iv:QpmIUY1qLoFfecDTFxV1tcgjz62pbRiDbR4uNP9ZmcA=,tag:pKkELmpm1kgmeMYuW3MgWQ==,type:bool]
devices_to_add:
    - device_id: ENC[AES256_GCM,data:T/wZ9+D7ssA8JlAzw6QBFbT8uGmlM4a/2gkbsXg9RQAq198SB4EVe2m+fBwXwMYtarYcYvriNjtSZMahvaEI,iv:WSHAgruj4bcDoiuiPjCn7E1h4YoH5HGf4S93Q3BH2NI=,tag:vcBGwKT/3iR14pOASSO98A==,type:str]
      name: ENC[AES256_GCM,data:57Oh+w8=,iv:UdC451tatbQtn8FGyzdv5R5TmGU5B9qdylkalTomsZg=,tag:FsX1f1lc2N8iyzcst1YX0Q==,type:str]
    - device_id: ENC[AES256_GCM,data:q+nOO/LaLOg/7Id5rGyAd2Fc5xc1XyKUAuLHPYK9SFRvx+AVKJnTwOmciuoJO7ClHVvHznQBkDj0/iLQhC4f,iv:JwG/4nQ2TUu1MQVM+96z16Rv6LPDfTRwRsrHf3jlshM=,tag:ztIaybeW9vlVVvHTUMAK9A==,type:str]
      name: ENC[AES256_GCM,data:MA7C7RT9a9r5Ho4=,iv:VBfQggwiHdaiS8w/d3Qy+gNR7+EAOwWwixE/F6QRuv4=,tag:AZ/sl7jKoPZ9uQJLSWDtIA==,type:str]
    - device_id: ENC[AES256_GCM,data:ozF1fsjqP4kt7xjhjXTrpR9aFYmem2OE1/0Yh7i8SLvTg/4kO0ZkkX+F9qHg2tf9dBdYRA7k7TS6svEzDAaj,iv:6nNRVYK5CuJVo1nO6ndxhYl5aqp2tw/cSpAkk8DFmkY=,tag:gKODgKcLKMimuBJMNylMDw==,type:str]
      name: ENC[AES256_GCM,data:pyiiKpOZ2sM3,iv:uJS0kP/1TxnZe4Nm8VA+SGfybaegy9KSgviBmBF04fA=,tag:eUjdTp/yQW514gg00Hs6Pg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:51:11Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEY6sylQbMXDjP70Tbf3Vb8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMz/VIoPXfdDqD6/bDAgEQgDvCjxiBOzNcSHR1Ps8SRnRqk1iV54YmWkboHvtxoFuRA/9/z0b3YZ0rL5eZ+i9R96pH/Nl8WLXnc6PY1g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeDMySDNoYVJ4bWsvS3RT
            ZDYxeDl3aDhMclQ1Y0g1SklmVjdyZFlPMkYwCmpZR3ROekl1dWtrN1kvbllJUXdp
            aUVzQi9QZFR6Zll0L0ZlelA2bWJqdGMKLS0tIDQwUHpiOXhnYnRkNkFlVzQ0b3FH
            Y1ZUeVF1dk5LeHlQWGI2RGxIeHhNTUkKwo613fvaEah66gkkEflZj8uKi69ieV/w
            aSUJUNDpc5nTPsbRmTItCALHreXAXmKapDq2H7ZCyG+lnWkJxHLtGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:51:12Z"
    mac: ENC[AES256_GCM,data:7zry3AitVT4zn3eHzK3ofVfRNOuZYMLMHDC9y8Xdzk2FH9+Iunk+cBfbJqiJd5X8ZfEEqC4b48w9anIpSbyySZuUMA+ShZsMDFp/3KxjUCEc9NsFCqM5QhSTxW0Vcw1FrKx3nLQ2XULEqNc5Aq8xQ+mE3ddsptDJq/TZgNScA+k=,iv:XUnOc08HnflRpOV9/q6khwkwQZgI3uy0kkmP8hE/2is=,tag:VannCymb3X/yaDCG65RS+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
