ansible_host: ENC[AES256_GCM,data:pTD8AAnWFdgg0uTUZA==,iv:7JH3iBZqwhFY170c55NzoR/iexFNAz5ipv/S9JskLHE=,tag:bZtlbuHm/J51ACkiwSBGZw==,type:str]
ansible_user: ENC[AES256_GCM,data:P3/M2j+R,iv:1wcYfyx5PSwfb6zMS5ToveMA6SzEE8B9MuF11NOQMlY=,tag:+6iImB0UBVOGw2mjiUBOVg==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:NnI8GzXY7cSj8w==,iv:rO7L0WR5Z39ffdPqb+W1jfaTmiKR0uR66bhBelVOQjg=,tag:ndrwhnI7h9JuIfenahQFRg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-22T14:36:13Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwFsB/PEyv0AwcaASo2s5oJhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMv5Qlya3Rp0LDIcfNAgEQgDvrIKFr9qx9euHOnrj2gLu9ZR2p7QO43mzdkqqS4ibsHrb9n4uOyge+GYWx0X23KAr87UPZ0nHbyV6LEw==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXlsQk0wSlYzZGRWQzRm
            NG1YMi9rc3lhNGkzRXFpNlRibmYxT1pVOVFNCnFBTE0vcDVXc3ZLRk43TFVtZVRn
            QlhmWmVmQ1V1ZG5sazVWVlFxeHk4ZW8KLS0tIGRMUnNGNCtob096aThSdVNzbmx2
            d2NCQ0gxcGpFREJBSm9GaXVVTjZwMUUKQ+E0PHTzRbO1h1znc7vHNNAhhOVbIVJ0
            zuOJDxMRQrujyoOXFGTeH6b1wd73lbHLbYkK5sBJreoXnRETia8DoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T14:36:15Z"
    mac: ENC[AES256_GCM,data:fOPiv3uf1mHfEsFuPLJKumUtDVxuE/j8WBshGEz2agLnsj/ECgeeWvJXI+BQXQtmRH8zTdwvQ/lb6YB+U0YS4rtzKDmvbZmAewGXjzgfzQnPgin5+4b/nELf/9dhcK8jwsCzbei67psnUiEw0jIUPQNf6nlmgZ0jVib0rviIcSc=,iv:BlHUBaUQin1OwHI+ZVKZ/j/4ssiuiyTJ+qRe+S75HQo=,tag:zPKkxfELDXbC8TefL6gLhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
