ansible_host: ENC[AES256_GCM,data:ZTEHReUCnCG+MAo=,iv:2ukCY7A6xxjiTb/bOIgePuoboIp1e6AsfotES2+TDpM=,tag:DDqXMy5lnhfVKCDhrWbr2Q==,type:str]
ansible_user: ENC[AES256_GCM,data:xYgMDCQO,iv:harU/OPEJPQ9v7Ltvv3ZGdbBePyd/rQMV2aJtePZO2o=,tag:o/XrHfhmSRm510ikjG34bA==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:W3bEB2ypXVd1E60N19pRig==,iv:2B5CgE4CmSVKsvxaH4nkpnzZiqVyFbgwKRWPW+AtguM=,tag:So6S+URvl/JU+mRt1e5AYw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:46:46Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwG+HPS6jfRUvkc+6SXwB8RYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgnT+sJ/+9STpaVxfAgEQgDuIsKv1bK9iJB5Wy3CsDYlHKfqaw/uqGLvJOGR+fqHjUer9Lm1tocntz8NZ6stC+B5odS+AafH6uqfllg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYjMwMmpacTVMV3FtbDc3
            OW9JWmNkRmZYMkRhUXUzcU1wSTBsM2FoK3g0CnB1cU9XdjhpSUFJWFR2QVVuWDBx
            T29HZTZoWTRJS25RWm5XWVl5SmxPV28KLS0tIGxWc0ZMVFMza2lyMGZ4WlRVaVM0
            eFNjTGc0S3pDVWoyMC9ENTJzQk1YR2sKNBZB3ke6ee/OwL2cidr+hPKh456MJ7cS
            cqAJPpkVdKnr6RTnWAMY309dZm4EKOBggLe7N5wrl8JUZGiNT23BqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:46:48Z"
    mac: ENC[AES256_GCM,data:JiIYWObQdP0/7UnD9TOnx4iN9mB2sezTkgE80PWf3Z/cvaweCH4RKxlDyxilVpHddQDMhYnqU62a2btLMZ/sn6eVgfy2UAQQp++dNvlF+b/uEVF2NvW9W/UlD+hLlPJ2Bs9o3+9mWJVZ8Acnnjxsc+LerKQCY65QtDZSMCAhR0w=,iv:6/qQ6WvyC9+NxIucRx+5NauouhQPyCZzI+aM9fEswAU=,tag:0rP504oklTtHy/3/xd+b+w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
