ansible_user: ENC[AES256_GCM,data:TUk8r5C962UfmGdw,iv:9Il6RDrwUm8qGzhUaxvjDlT4zZNVuX8d5LAIHsuxYXk=,tag:5IFKY6Xs/mPbl8EUgdR9pg==,type:str]
devices_to_add:
    - device_id: ENC[AES256_GCM,data:wElHCS5IzztqI7jhlFf63Bb7+NqtDrKnXeJk60Ri51w4O5n/ArUO2PXFTui4g2TNCscI1scK1r6lWxGDDRHn,iv:uBtlMhfuc0LGV+ZO6siyEzvk3mPbX8P1U/QuDkR+gJw=,tag:wN67TL0V+ThDGCadc3eXSQ==,type:str]
      name: ENC[AES256_GCM,data:+gXYuTA=,iv:NDWsI+ox1tSsDin79ZKfrNh8SbyNZReeIDUfjQhUbHs=,tag:2+dOxukGQjWAPy8kPw8h6g==,type:str]
    - device_id: ENC[AES256_GCM,data:Tgwg01O/Ujg612ruDqI0dZsU0FkOr37RvBusO2PowDodyX+nenwSXI9bp/NhSEonwf4rN2wY9qu0MbJirlg7,iv:m8Y2RSh9kpBcwES8pBSvfbRPOBzB2ML3tkREt/ZeOQk=,tag:VYejpbq30RiH3ZV5IUzkAg==,type:str]
      name: ENC[AES256_GCM,data:Mc/neP+mgHXimWs=,iv:yuD/kP0SVOc00oMm0T7P7w2cnMzDSgMlGTHfdoPF6zI=,tag:9HujCWlzX/erRpvDHP4/Cg==,type:str]
    - device_id: ENC[AES256_GCM,data:LgYV2FLNKLStpMSZi2h7ZLgK1pFhCWHwc89Y9dQp/40sD3DtCGP8b/xdSSjxUMMYVCJVXyGJvBpvgmmuvx5h,iv:TOuT+WWczrexHPgbpj90GFF5ovPJQ3Bu2+IrdjHsSqE=,tag:2Tdu0a+dNqMUvH3ZBDlnTw==,type:str]
      name: ENC[AES256_GCM,data:BiRfTq4fm8bB,iv:/9zw9ei8+HoPEXmhr5ZfN41wSv9dqWqlcAsbay7wJ3Y=,tag:ujc0uP8mKqxVnAACbLzLig==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:52:57Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwGTBjqM7HNpHy1Kkv+3bSPTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsoGxhFWHgd4lGM+5AgEQgDsVJ3topZoLvNq3nGaQSFnXp/FhjcvIVnlz53WN/LmyMCwXNJg2GLLgdZmwqnQGwRzziuffTUZ9g7yJzw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNG82aTB6OGwwZlRMc3A5
            RDB1TFhaQjFJVHJ0YlM5KzlmK1VCWXBqcGtrCitHN2o2YXdlaE5EVmxSTEZ4NzNw
            QTdtckh2VEMyVDhGQS8wcjlRR2Yzb1kKLS0tIGMvbFl6UVp2cHRjQnFnRlYvOWU1
            S2hBcEwxcTVUd3hRMFdqUHJleHZrOVEKUc2AF2g57VoWga4aaFF52UHKqe5x/9/s
            rDQwf+KyWjHz2JX8eFuKr0uh4uNmRaGKulVno6osBGk72SrgEYtsjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:52:59Z"
    mac: ENC[AES256_GCM,data:/j3ipoe8brgn5Zhw5KFOhPd85jAetqxNDeSwQ6z1GKOfbFGsthXcnAM3qxu+PzmDOUv+N6AMiHD4FZUiddXGtSO3Fnxr6GWgE1bAQn3S9VsKMFk9Ek6F+p0IlAZmTgtSjiyeOxK2TOmwwD/Z/vhKhyA681QSPj6KthwEBQbdS5s=,iv:LUf2I0TJXzFPtPGctf25mLoClP/8RsIJ4iSa5gT+IHg=,tag:L7tM9TvNDhn3x8/SUX33qA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
