---
- name: playbook de teste
  hosts: all

  roles:
    - role: dev.utils
      become: true
      tags:
        - dev

    - role: yazi
      tags:
        - dev
        - yazi

    - role: syncthing
      become: true
      tags:
        - syncthing
        - infra

    - role: vscode
      become: true
      tags:
        - dev
        - vscode

    - role: chezmoi
      become: true
      tags:
        - dev
        - chezmoi

    - role: asdf_cli
      become: true
      tags:
        - dev
        - asdf

    # - role: cloudalchemy.node_exporter
    #   become: true
    #   tags:
    #     - infra
    #     - metrics

    - role: geerlingguy.docker
      become: true
      tags:
        - docker

    # - role: slack
    #   become: true
    #   tags:
    #     - dev

    # indicator-sysmonitor uses Ubuntu PPA - skip on Arch
    - role: indicator-sysmonitor
      become: true
      when: ansible_os_family == 'Debian'
      tags:
        - utils
