---
# Setup SOPS + age encryption for sensitive files
#
# Usage:
#   ansible-playbook -i hosts.yml playbooks/setup_sops.yml -l localhost
#
# After running, you can encrypt files with:
#   sops -e hosts.yml > hosts.sops.yml

- name: Setup SOPS encryption
  hosts: all
  gather_facts: yes

  roles:
    - role: sops_setup
      tags:
        - sops
