ansible_user: ENC[AES256_GCM,data:sUgnWeF6,iv:qrKIfRCd0awB7WDHflcG9ZZnqPWzs07Q0IGMaLxBeDw=,tag:8ZE+F6d+ZlFtY1fbqURShQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:48:12Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEa03uuf7S6hFyuRStUW1YuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfPgUDcu85kFXQWgXAgEQgDucUerzuP6t7myYVaS1Emry3AcXx2IpipruhVBZLHOVCZlfGkh1Z8cbhVTU8wd3TrOAi4TRVuhzFPZpaA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRWthdDRaUU40UUd6eFZ5
            VExZRDRwUVJ0QTlOdUNWQWJBUDVqaU5pMHdZCmhBUmJWRVpSRmdKVkdON0JidVVI
            WTdKVVlJTTJRbHFsbmtJY2JPWUV4VzgKLS0tIEx5c0pPbFYvWGcxTXp1Y0tXYXF2
            L3Q5NFQ2NUhQSVIxYTlLSHZ1bWtwL1EKwjCql/O1Gh9VFy7DxoKa/SXQsd34Fllm
            s205JvOdfNy1YuHnCfIFZ0Iz+OJF56WrxevadwSHFlXgRMiQUAtxPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:48:13Z"
    mac: ENC[AES256_GCM,data:Kb4e/EujGJzEAHh0ASdgJZe26S8LhqJLislbxw3PqASXySPGUUnqtuim1w3slPpLCTq4F2zM1Req+v9pfp+HjvtCbJlcA29zM36AOMsePhnhKWO6TlHHaL5BhiLfUg5ujnCYoZe9QxUMQpOzqYzt0yoJCaO26dtF6Nm/W7CvdZQ=,iv:BCKQDyoTi+75b36qttTNnhO+jtbvdsMkwdxd//LZ/68=,tag:OhmYA3vwWRnmajWwnfGntA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
