ansible_ssh_common_args: ENC[AES256_GCM,data:Uf3BgT5LF29pMkX2h8NLxfet8g==,iv:5SsoaB5CeAhXwxSsAM53hW+FcD2x5l8Is8fdipcC05c=,tag:DsUpN+KKONzdVwSglH/6yQ==,type:str]
chezmoi_github_username: ENC[AES256_GCM,data:8zuiLKwd3uwIAbpZ,iv:rVb5PbDCaV5WVCri0+jkb/BS53TbSpl7gjsUxVJmcWA=,tag:pm2iQmfQLkUKgMMym+FiaA==,type:str]
atuin_username: ENC[AES256_GCM,data:X+nvGuIFBehEUIVF,iv:hOyeatHXW+Qa10NFE1AmQLH0upFGqylXhuV1o8+bu/8=,tag:Ulf7fB6v4WNIB2OPla8p2w==,type:str]
atuin_password: ENC[AES256_GCM,data:NGiNqAwFH7clAcKg1G8muJiH0Vk=,iv:kLm13MDY4wMmKLKCtSHvaudO2SKqb3WFmbKAoY9hBJw=,tag:ZCO68cCeuV/sWn5OvRBORA==,type:str]
atuin_email: ENC[AES256_GCM,data:iVGuTQWsYdSd7yR3qo9/VOs43VtQwh9XuzEI0tg=,iv:7VUVjHKEM8dmA/tNQaYmYoic6+yAqUelF3+hemMmsnM=,tag:I5wXkREmkCNWjnevDRQMOA==,type:str]
atuin_key: ENC[AES256_GCM,data:+1Zi3Ic9zrpWpeA4qbZ1xllLu2lhqM7Te/bjt3L36CGauAznizOdU7vm38XGouipftSjIZXa8Ht5BQap8HPcx8WisoxG6NGYN+Dr6yek1OCXo/QMoC3ddblVrsL5062RSC6/UEUfbkadxW0oq8qQZHUfS0/HnZ1X5zLm1jYzQxc+JXwKLiGkTvZuV2HOyh8zwLaZWsk=,iv:W5QyoS6F+a8Uku7quplhqtSZ++0xl5KIlapIkjuLOiU=,tag:jli/grklIhvV+MRyJ0+9+g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-16T20:43:28Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwEAdABXzWUCGAv4xL+TgPOTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgmkYc4bcjrSxOfCxAgEQgDvNUKT1pf4+/wpSjexDbGFPnWYk7lLBjhgb9xufhpd5uK0NzEJT58CbSJloR74+I8UH7FrO/ivM8scwRQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS0ppTnNlOEFNVE8vV1hj
            bFNadWg4YW9vcDhZaHhRaHNTQWJhRGo2M1hFCklJa2NsRjVFQVNCeWpKamxKZGgy
            ZEZEbWVMTll5bXN5V3dxS1hpYlVod2MKLS0tIHJjMTBqVmp3enlRSG0wMVJiMi8v
            K28rZ0Z6WlUzNVA5bkV2d2RiT2VyM0kK4OKBaAmRouVbR9P9hwjsJaabjXVDo9PZ
            KPQvdG69elr3cDsuntMCRdyFK/snMWZJ59e95938HfrFmmdQyfD9gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:43:29Z"
    mac: ENC[AES256_GCM,data:zejtgMJYRfPNu7cKdonvbw5+Co93OMQ/LF0aQovmpeWU9Twu4IOBTSWuv6XmywkJGiM7dLrXOmeSOWJpPnxBqIkh46KQTDclXGTqbdp3zwefFbSga0EB4i/y+Eh40FQB4jfqp67B4D9DEtcd3Kn3rFR/IMVoF7ot9f6vt43muzI=,iv:RIspRNuwvMtQTakqI9LUzKojcKhaGk5dv3YpqR0wj+k=,tag:sx/nf5Vld6CMsJ/HRD8Plw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
