name: Lint YAML
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  - pull_request
jobs:
  yaml_lint:
    name: "YAML Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
      - run: echo "ğŸ This job's status is ${{ job.status }}."
